Update for FreeBSD Python
I don't know if this is importan to other OS's, But for Freebsd numpy needs to be loaded before cv2 to avoid:

ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "./facedetect", line 8, in <module>
    import cv2
ImportError: numpy.core.multiarray failed to import